version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "3000:3000"
    volumes:
      - ./nginx/nginx.local.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
      - instructor
      - student
    networks:
      - unpuzzle-network

  # These are placeholders - in dev mode, you'll run these with pnpm
  # This file shows how they would be containerized for consistent dev environment
  client:
    build:
      context: ./apps/client
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    networks:
      - unpuzzle-network

  instructor:
    build:
      context: ./apps/instructor
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3002"
    networks:
      - unpuzzle-network

  student:
    build:
      context: ./apps/student
      dockerfile: Dockerfile.dev
    ports:
      - "3003:3003"
    networks:
      - unpuzzle-network

networks:
  unpuzzle-network:
    driver: bridge