[build]
builder = "nixpacks"
buildCommand = "cd apps/instructor && npm ci && npm run build && cp server.js .next/standalone/"

[deploy]
startCommand = "cd apps/instructor && node server.js"
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5