[build]
buildCommand = "cd apps/instructor && npm install --production=false && npm run build"

[deploy]
startCommand = "cd apps/instructor && node server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
NIXPACKS_NODE_VERSION = "20"