[build]
builder = "nixpacks"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "instructor"
source = "apps/instructor"

[services.variables]
NODE_ENV = "production"
PORT = "3000"