[build]
builder = "nixpacks"

[deploy]
restartPolicyType = "on_failure"

# Client App Service
[[services]]
name = "unpuzzle-client"
source = "apps/client"

[services.build]
buildCommand = "npm ci && npm run build"
startCommand = "npm start"

[services.variables]
NODE_ENV = "production"
NEXT_PUBLIC_API_URL = "https://dev.nazmulcodes.org"

# Instructor App Service  
[[services]]
name = "unpuzzle-instructor"
source = "apps/instructor"

[services.build]
buildCommand = "npm ci && npm run build"
startCommand = "npm start"

[services.variables]
NODE_ENV = "production"
NEXT_PUBLIC_APP_SERVER_URL = "https://dev.nazmulcodes.org"
NEXT_PUBLIC_M1_SERVER_URL = "http://localhost:4000"
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = "pk_test_aG9wZWZ1bC1za2luay0xNy5jbGVyay5hY2NvdW50cy5kZXYk"
CLERK_SECRET_KEY = "sk_test_gAzXahOCkEUgdHPOewgALZ7vCtJ8DkyKNxc1zrveva"
CLERK_SIGN_IN_URL = "/sign-in"
CLERK_SIGN_UP_URL = "/sign-up"
CLERK_AFTER_SIGN_IN_URL = "/instructor/editor"
CLERK_AFTER_SIGN_UP_URL = "/instructor/editor"

# Student App Service
[[services]]
name = "unpuzzle-student"
source = "apps/student"

[services.build]
buildCommand = "npm ci && npm run build"
startCommand = "npm start"

[services.variables]
NODE_ENV = "production"
NEXT_PUBLIC_API_URL = "https://dev.nazmulcodes.org"