[build]
builder = "nixpacks"

[deploy]
startCommand = "pnpm start"
restartPolicyType = "on_failure"

[[services]]
name = "client"
source = "apps/client"

[services.build]
buildCommand = "cd ../.. && pnpm install && pnpm build --filter=@unpuzzle/client"
startCommand = "cd apps/client && pnpm start"

[[services]]
name = "instructor" 
source = "apps/instructor"

[services.build]
buildCommand = "cd ../.. && pnpm install && pnpm build --filter=unpuzzle-ai-frontend"
startCommand = "cd apps/instructor && pnpm start"

[[services]]
name = "student"
source = "apps/student"

[services.build] 
buildCommand = "cd ../.. && pnpm install && pnpm build --filter=@unpuzzle/student"
startCommand = "cd apps/student && pnpm start"