[build]
builder = "nixpacks"
buildCommand = "cd apps/instructor && npm ci --only=production --loglevel=error && npm run build"

[deploy]
startCommand = "cd apps/instructor && node server.js"
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "instructor"
root = "apps/instructor"

[services.healthcheck]
path = "/api/health"
interval = 30
timeout = 10
retries = 3