[[services]]
name = "unpuzzle-client"

[[services]]
name = "unpuzzle-instructor"

[services.unpuzzle-instructor.variables]
NEXT_PUBLIC_APP_SERVER_URL = "https://dev.nazmulcodes.org"
NEXT_PUBLIC_M1_SERVER_URL = "http://localhost:4000"
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = "pk_test_aG9wZWZ1bC1za2luay0xNy5jbGVyay5hY2NvdW50cy5kZXYk"
CLERK_SECRET_KEY = "sk_test_gAzXahOCkEUgdHPOewgALZ7vCtJ8DkyKNxc1zrveva"
CLERK_SIGN_IN_URL = "/sign-in"
CLERK_SIGN_UP_URL = "/sign-up"
CLERK_AFTER_SIGN_IN_URL = "/editor"
CLERK_AFTER_SIGN_UP_URL = "/editor"
NEXT_PUBLIC_BASE_PATH = "/instructor"

[[services]]
name = "unpuzzle-student"