services:
  - type: web
    name: unpuzzle-client
    env: node
    root: apps/client
    buildCommand: npm ci && npm run build
    startCommand: npm start
    plan: starter
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://dev.nazmulcodes.org

  - type: web
    name: unpuzzle-instructor
    env: node
    root: apps/instructor
    buildCommand: npm ci && npm run build
    startCommand: npm start
    plan: starter
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_APP_SERVER_URL
        value: https://dev.nazmulcodes.org
      - key: NEXT_PUBLIC_M1_SERVER_URL
        value: http://localhost:4000
      - key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        value: pk_test_aG9wZWZ1bC1za2luay0xNy5jbGVyay5hY2NvdW50cy5kZXYk
      - key: CLERK_SECRET_KEY
        value: sk_test_gAzXahOCkEUgdHPOewgALZ7vCtJ8DkyKNxc1zrveva
      - key: CLERK_SIGN_IN_URL
        value: /sign-in
      - key: CLERK_SIGN_UP_URL
        value: /sign-up
      - key: CLERK_AFTER_SIGN_IN_URL
        value: /instructor/editor
      - key: CLERK_AFTER_SIGN_UP_URL
        value: /instructor/editor

  - type: web
    name: unpuzzle-student
    env: node
    root: apps/student
    buildCommand: npm ci && npm run build
    startCommand: npm start
    plan: starter
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://dev.nazmulcodes.org