# nixpacks.toml
[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = ["npm ci --loglevel=error"]

[phases.build]
cmds = ["npm run build", "cp server.js .next/standalone/"]

[start]
cmd = "node server.js"

[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"
PORT = "3000"
HOSTNAME = "0.0.0.0"