# nixpacks.toml
[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = ["npm ci --loglevel=error"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "if [ -f .next/standalone/server.js ]; then cd .next/standalone && node server.js; else node server.js; fi"

[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"
PORT = "$PORT"
HOSTNAME = "0.0.0.0"