# nixpacks.toml
[phases.setup]
nixPkgs = ["nodejs-20_x", "npm-10_x"]

[phases.install]
cmds = ["npm ci --loglevel=error"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node server.js"

[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"